IbenFP935/get_the_book

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card_product.scss, app/controllers/books_controller.rb, app/views/books/index.html.erb
card product added as a component and upgrades on the index
=> index cards

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card_product.scss, app/views/books/index.html.erb
=> index features

app/controllers/books_controller.rb, app/views/books/show.html.erb
- Added show method in books controller
- Show html.erb page defined
=> show view page for branch

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
Button from home page to books_path
=> Home button

app/controllers/books_controller.rb, app/views/books/show.html.erb
Add the edit function
Fixed table headings
=> edit route addition

app/controllers/application_controller.rb, app/views/shared/_navbar.html.erb
having fixed the user login and signup
=> devise form fixed

app/views/books/edit.html.erb
- edit.html.erb form added for edit feature
=> edit form added

app/views/books/edit.html.erb
=> resubmitting changes

app/controllers/books_controller.rb, app/models/book.rb, app/views/books/show.html.erb
i have added the delete button to the show view and also implemented the destroy action in the index so that the user can delete books
=> delete button and destroy action features added

app/controllers/books_controller.rb, app/views/books/show.html.erb
=> Book update action

app/assets/stylesheets/pages/_about.scss, app/assets/stylesheets/pages/_index.scss, app/views/pages/about.html.erb, app/views/pages/home.html.erb, config/routes.rb, package.json, yarn.lock
=> Created the about page and its contents

app/views/books/index.html.erb
=> edits to index views

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_card_product.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_index.scss, app/views/books/index.html.erb, app/views/pages/home.html.erb
=> Experimental stuff

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/controllers/application_controller.rb, app/controllers/bookings_controller.rb, app/controllers/books_controller.rb, app/policies/application_policy.rb, app/policies/book_policy.rb, app/policies/booking_policy.rb, app/views/bookings/new.html.erb, app/views/books/index.html.erb, app/views/books/new.html.erb, app/views/books/show.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb, test/policies/book_policy_test.rb, test/policies/booking_policy_test.rb
complete implementation of pundit
=> pundit implemented

app/controllers/bookings_controller.rb, app/views/bookings/index.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb, db/seeds.rb
=> bookings index

app/views/books/show.html.erb
=> Added the link

app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, app/views/books/show.html.erb
=> Bookings view

app/models/book.rb, app/models/booking.rb, app/views/books/index.html.erb
When book has a booking it will display non-available and when it doesn't it will display available for rental
=> Method to check if a book is available for rental or not works

app/controllers/books_controller.rb, app/views/shared/_navbar.html.erb
Iben ya tengo la search bar running!
=> Search bar

app/views/pages/about.html.erb
=> minor edits to about page

app/assets/stylesheets/application.scss, app/assets/stylesheets/config/_colors.scss, app/views/pages/home.html.erb
=> front page html css edit

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
Hi Iben !
I just centered the nav - bar
=> Centered search bar

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/pages/_index.scss, app/views/books/index.html.erb
=> View index

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_button.scss, app/views/pages/home.html.erb
- homepage front end touches
- cards & images added
=> Gtb homepage frontend

app/assets/stylesheets/components/_table.scss, app/views/books/show.html.erb
Iben,
Did some changes inside the show page
=> Changed the show-page

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_index.scss, app/views/bookings/index.html.erb, app/views/books/index.html.erb
Bookings cards almost complete. Need to add delete and update functions
=> Profile view

app/views/pages/home.html.erb
Button moved to center of banner. Home page
=> Button moved to center

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_forms.scss, app/assets/stylesheets/pages/_index.scss, app/views/bookings/index.html.erb, app/views/books/index.html.erb, app/views/books/new.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
=> General changes

app/assets/stylesheets/components/_icons.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_table.scss, app/views/books/show.html.erb
Iben, te mando los ultimos cambios a show
=> Final changes to show

app/views/books/index.html.erb, db/migrate/20200619200233_add_photo_url_to_books.rb, db/schema.rb, db/seeds.rb
=> seeds photos
